Searching for an element in a linked list C++
DecodersCommunity/dsa-library pull request #24
Opened 2022-10-01 14:24 UTC by geoffgeorgein

Contributed by - Geoff George <geoffgeorgethommana@gmail.com>

2022-10-01 16:28 UTC, harshit-sharma-gits commented on Data Structures/Linked List/linked list search.cpp
> +    14->21->11->30->10 */
I believe this is a comment, please make it so

2022-10-01 16:29 UTC, harshit-sharma-gits commented on Data Structures/Linked List/linked list search.cpp
> +    search(head, 11) ? cout << "Yes" : cout << "No";
Can you be more elaborative on what the output is telling us?

2022-10-01 16:30 UTC, harshit-sharma-gits commented on Data Structures/Linked List/linked list search.cpp
> +#include <bits/stdc++.h>
Please take a look at #12 
You have to add your name, email in the specified format in the first line as comment

2022-10-01 16:32 UTC, harshit-sharma-gits requested changes
I have added comments in your file, please resolve them

2022-10-02 08:06 UTC, geoffgeorgein commented
Added the required changes

2022-10-04 06:19 UTC, harshit-sharma-gits commented on Data Structures/Linked List/linked list search.cpp
> +#include <bits/stdc++.h>
Add you name, email in first line as well @geoffgeorgein, see issue #13

2022-10-04 16:40 UTC, harshit-sharma-gits approved these changes

2022-10-04 16:40 UTC, merged