Update README.md
DecodersCommunity/dsa-library pull request #45
Opened 2022-10-01 18:39 UTC by 55ritesh

2022-10-01 18:46 UTC, harshit-sharma-gits requested changes
@55ritesh You are not supposed to edit the code in the README file. Revert it to its original state, and place you code in `./Tree/tree.cpp`

2022-10-01 18:51 UTC, 55ritesh commented
changed

2022-10-03 06:20 UTC, harshit-sharma-gits requested changes
You again have created an un-extensioned file. Please rename the file to `tree.cpp`

2022-10-03 06:20 UTC, harshit-sharma-gits commented on Data Structures/Tree/Implementation of tree data structure
> +## Tree Data Structure
You also have to add your name, email in the first line as a comment in a specified format. See issue #12

2022-10-03 08:56 UTC, 55ritesh reviewed
made the changes

2022-10-04 06:20 UTC, harshit-sharma-gits approved these changes
Now its cool, approving.

2022-10-04 06:21 UTC, merged